import type { NextPage } from "next";
import Head from "next/head";
import ArticlePreview from "./components/ArticlePreview";
import MainTitle, {
	ArticleHeading,
	ArticleHeadline,
} from "./components/Headings";
import ImageFrame from "./components/ImageFrame";

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Nathereen</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<MainTitle text={"Nathereen"} />
				<section className="articleColumn container">
					<ArticlePreview
						ArticlePreviewImage={
							<ImageFrame
								imageSource={"https://source.unsplash.com/random"}
								imageSizeBehavor={"fill"}
								classValue={"articlePreviewImage image"}
								imageWidth={500}
								imageHeight={500}
							/>
						}
						ArticlePreviewHeading={
							<ArticleHeading
								text={"Some Article Title That Describes A Point"}
							/>
						}
						ArticlePreviewHeadline={
							<ArticleHeadline
								text={
									"Some Article Headline that supports the Heading and Photo of the post"
								}
							/>
						}
					/>
				</section>
			</main>
		</div>
	);
};

export default Home;
