import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import { Button } from "@mantine/core";
import { Context } from "react";
import ArticlePreview from "../components/ArticlePreview";
import MainTitle, {
	ArticleHeading,
	ArticleHeadline,
} from "../components/Text/Headings";
import ImageFrame from "../components/ImageFrame";

type HomeProps = {
	ArticleItems: number[];
};

const Home: NextPage<HomeProps> = ({ ArticleItems }: HomeProps) => {
	/* Pass Down a left or right align class to 
    even and odd Article's when mapped to render 

  */
	for (let i = 0; i < 29; i++) {
		ArticleItems[i] = i;
	}
	return (
		<div>
			<Head>
				<Link href={"/AdminDash"} passHref={true}>
					<a>
						<title>Nathereen</title>
					</a>
				</Link>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<MainTitle classValue={""} text={"Nathereen"} />
				<section className="articleColumn container">
					{ArticleItems &&
						ArticleItems.map((article, index) => (
							<ArticlePreview
								key={index}
								path={`/post/${index}`}
								ArticlePreviewImage={
									<ImageFrame
										id={`articlePreview__${index}`}
										imageSource={"https://source.unsplash.com/random"}
										imageSizeBehavor={"fill"}
										classValue={`articlePreviewImage image`}
										positioningClassValue={
											index % 2 ? `articleImageRight ` : `articleImageLeft`
										}
										FrameClassValue={`imageFrame`}
										imageWidth={500}
										imageHeight={500}
									/>
								}
								ArticlePreviewHeading={
									<ArticleHeading
										classValue={
											index % 2 ? `articleHeadingLeft` : `articleHeadingRight`
										}
										text={"Some Article Title That Describes A Point"}
									/>
								}
								ArticlePreviewHeadline={
									<ArticleHeadline
										classValue={
											index % 2 ? `articleHeadingLeft` : `articleHeadingRight`
										}
										text={
											"Some Article Headline that supports the Heading and Photo of the post"
										}
									/>
								}
							/>
						))}
				</section>
			</main>
		</div>
	);
};

export default Home;
export async function getStaticProps(context: Context<{}>) {
	return {
		props: {
			ArticleItems: [],
		},
	};
}
